# Generated by Django 5.0.6 on 2024-06-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline_event_detail',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='timeline_event_detail',
            name='degree',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
