# Generated by Django 5.0.6 on 2024-06-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0005_alter_timeline_event_timeline_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline_event',
            name='event_add_datetime',
            field=models.DateTimeField(null=True, verbose_name='datetime event added to timeline'),
        ),
    ]
