# Generated by Django 5.0.6 on 2024-06-14 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0006_alter_timeline_event_event_add_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline_event',
            name='event_add_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timeline_event',
            name='org_name',
            field=models.CharField(max_length=50, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='timeline_event',
            name='role_name',
            field=models.CharField(max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='timeline_event_detail',
            name='timeline_event_id',
            field=models.ForeignKey(db_column='timeline_event_id', on_delete=django.db.models.deletion.CASCADE, to='resume_builder.timeline_event'),
        ),
    ]
